In [18]:
import numpy as np

In [19]:
vectors=np.array([
    [1,2,3],
    [2,3,4],
    [8,8,9],
    [1,0,1],
    [5,4,3]
])
query=np.array([2,2,3])
print("Dataset Vectors:\n")
print(vectors)
print("\nQuery Vector:\n")
print(query)

Dataset Vectors:

[[1 2 3]
 [2 3 4]
 [8 8 9]
 [1 0 1]
 [5 4 3]]

Query Vector:

[2 2 3]


In [26]:
def cosine_similarity(a,b):
    dot_product=np.dot(a,b)
    norm_a=np.linalg.norm(a)
    norm_b=np.linalg.norm(b)
    return dot_product/(norm_a*norm_b)
print("\ncosine similarity scores\n")
scores=[]
for i, vector in enumerate(vectors):
    similarity=cosine_similarity(query, vector)
    scores.append(similarity)
    print(f"vectors {i+1}:{similarity:.4f}")
nearest_index=np.argmax(scores)
print("\nNearest Neighbor")
print("Index:",nearest_index)
print("Vector:",vectors[nearest_index])
print("Similarity score:",round(scores[nearest_index],4))


cosine similarity scores

vectors 1:0.9723
vectors 2:0.9908
vectors 3:0.9898
vectors 4:0.8575
vectors 5:0.9261

Nearest Neighbor
Index: 1
Vector: [2 3 4]
Similarity score: 0.9908


In [25]:
print("\nEuclidean distance\n")
distances=np.linalg.norm(vectors-query,axis=1)
for i,d in enumerate(distances):
    print(f"vector{i+1}:{d:4f}")
nearest_distance=np.argmin(distances)
print("\nNearest neighbor(euclidean distance)")
print("Index:",nearest_distance)
print("Vector:",vectors[nearest_distance])
print("Distance",round(distances[nearest_distance],4))





Euclidean distance

vector1:1.000000
vector2:1.414214
vector3:10.392305
vector4:3.000000
vector5:3.605551

Nearest neighbor(euclidean distance)
Index: 0
Vector: [1 2 3]
Distance 1.0
